import styled from "styled-components";
import Head from "next/head";
import Header from "./Header";
import Footer from "./Footer";

export default function Layout({ children, togglePageActive }) {
  return (
    <>
      <Head>
        <title>Trip and bla</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header togglePageActive={togglePageActive} />
      <StyledMain>{children}</StyledMain>
      <Footer toggleActivePage={togglePageActive} />
    </>
  );
}

export const StyledMain = styled.main`
  max-width: var(--max-with);
  margin: var(--main-margin);
`;
