import styled from "styled-components";
import Head from "next/head";
import Header from "./Header";
import Footer from "./Footer";

export default function Layout({
  children,
  activePage,
  setActivePage,
  toggleActivePage,
}) {
  return (
    <>
      <Head>
        <title>Trip and bla</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header
        activePage={activePage}
        setActivePage={setActivePage}
        toggleActivePage={toggleActivePage}
      />
      <StyledMain>{children}</StyledMain>
      <Footer
        activePage={activePage}
        setActivePage={setActivePage}
        toggleActivePage={toggleActivePage}
      />
    </>
  );
}

export const StyledMain = styled.main`
  max-width: var(--max-with);
  padding: var(--main-padding);
  margin: var(--main-margin);
`;
