// import general things to run the app
import Head from "next/head";
import Image from "next/image";
// import components
import Header from "./Header";
import Footer from "./Footer";
// import components for styles
import styled from "styled-components";

export default function Layout({ children, togglePageActive }) {
  return (
    <>
      <Head>
        <title>Trip and bla</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header togglePageActive={togglePageActive} />
      <StyledMain>{children}</StyledMain>
      <StyledFooterImage
        src="/images/footer-70.png"
        sizes="100vw"
        style={{
          width: "100%",
          height: "auto",
        }}
        width="0"
        height="0"
        alt="Travel the world"
        loading="lazy"
      />
      <Footer toggleActivePage={togglePageActive} />
    </>
  );
}

export const StyledMain = styled.main`
  max-width: var(--max-with);
  margin: var(--main-margin);
`;

export const StyledFooterImage = styled(Image)`
  position: fixed;
  bottom: 0;
  z-index: -999;
`;
